Update `ES_HOST` to document TLS usage
mastodon/documentation pull request #1140
Opened 2023-01-03 01:03 UTC by ElanHasson

Explain how to use ElasticSearch endpoints that use TLS.

2023-11-24 17:57 UTC, vmstan commented
This should also probably be called out on https://docs.joinmastodon.org/admin/elasticsearch page as well.

2023-12-05 01:18 UTC, vmstan commented
@ElanHasson can you please rebase?

2023-12-05 05:48 UTC, ElanHasson commented
@vmstan should be all set. Feel free to change/add verbiage

2023-12-05 14:07 UTC, vmstan requested changes

2023-12-05 14:07 UTC, vmstan commented on content/en/admin/config.md
> +Host of the ElasticSearch server. Defaults to `localhost`. If using TLS, prepend the hostname with `https://`. For example: `https://myelastic.tld`.
Elasticsearch is proper usage. Also lets use example.com domain as proposed in #1227 for consistency.

```suggestion
Host of the Elasticsearch server. Defaults to `localhost`. If using TLS, prepend the hostname with `https://`. For example: `https://elastic.example.com`.
```

2023-12-05 14:07 UTC, vmstan commented on content/en/admin/elasticsearch.md
> +_Note_: If using TLS, prepend the hostname with `https://`. For example: `https://myelastic.tld`.
Same as above.

```suggestion
_Note_: If using TLS, prepend the hostname with `https://`. For example: `https://elastic.example.com`.
```

2023-12-05 15:06 UTC, merged