Admin roles
mastodon/documentation pull request #1268
Opened 2023-07-30 16:53 UTC by liamstojanovic

# Summary
A description of the roles and their management from the admin dashboard. Roles and their attributes are documented. Default roles present in a new server instance are identified and explained. Creation of custom roles, and editing existing roles are demonstrated with accompanying screenshots.

# Notes
- This page resides in the `~/content/en/admin` folder, which appears to be a rollup of installation, configuration, and maintenance of a server. It may be advantageous to organize the `admin` folder with high-level categorization, such as `Configuration/Installation` and `Maintenance`.
- I noticed other pages in the `admin` folder have `weight` properties. It was not immediately apparent what weight to assign my page.
- This page pertains specifically to managing roles through the web interface. 

# Related issue
fixes #1251

2023-08-21 10:42 UTC, andypiper commented
This looks good (I'm just checking locally to confirm everything is working as expected).

I think we probably need to think more broadly about (re)organising the Admin section of the docs, particularly since this useful new addition currently lives at the bottom of a long and slightly out-of-sequence topics under the Admin index in the sidebar.

2023-08-21 10:49 UTC, andypiper commented on content/en/admin/roles.md
> +When the database is seeded, roles are derived from the values present in  [`~/config/roles.yml`](https://github.com/mastodon/mastodon/blob/main/config/roles.yml).
trailing whitespace

2023-08-21 10:49 UTC, andypiper requested changes
`git apply` is reporting whitespace errors for 7 lines in the supplied new roles.md file.

2023-09-24 19:39 UTC, liamstojanovic commented
> `git apply` is reporting whitespace errors for 7 lines in the supplied new roles.md file.

To the best of my knowledge, I have rectified trailing and double whitespace in the `roles.md` file.

It was not immediately clear to me how exactly to use the `git apply` command to output whitespace errors, so apologies if that error is still present.

2023-12-07 18:22 UTC, vmstan approved these changes

2023-12-07 19:47 UTC, andypiper approved these changes

2023-12-07 19:47 UTC, merged