Add documentation for `attribution_domains`
mastodon/documentation pull request #1558
Opened 2024-11-13 17:38 UTC by c960657

Documentation for new `attribution_domains` API attribute proposed in https://github.com/mastodon/mastodon/pull/32730.

2025-01-16 08:38 UTC, ClearlyClaire requested changes
Thank you!
The added versions are inaccurate though!

2025-01-16 08:38 UTC, ClearlyClaire commented on content/en/entities/Account.md
> +4.3.2 - added
```suggestion
4.4.0 - added
```

2025-01-16 08:38 UTC, ClearlyClaire commented on content/en/methods/accounts.md
> +4.3.2 - added `attribution_domains` parameter
```suggestion
4.4.0 (`mastodon` [API version]({{< relref "entities/Instance#api-versions" >}}) 3) - added `attribution_domains` parameter
```

2025-01-17 08:19 UTC, oneiros approved these changes
Thanks a lot!

2025-01-17 08:47 UTC, ClearlyClaire approved these changes

2025-01-17 08:48 UTC, merged