Fix `force_login` type & more
mastodon/documentation pull request #894
Opened 2021-09-11 15:47 UTC by replicant64

Makes `force_login` of type `bool` & moves optional parameters to bottom of table for consistency.

2021-09-12 04:50 UTC, Gargron requested changes

2021-09-12 04:50 UTC, Gargron commented on content/en/methods/accounts.md
> +e="header" >}}
Typo

2021-09-13 10:18 UTC, replicant64 commented on content/en/methods/accounts.md
> +e="header" >}}
Fixed by 9179088

2021-09-13 15:55 UTC, Gargron approved these changes

2021-09-13 15:55 UTC, merged