Fix dead link
mastodon/documentation pull request #949
Opened 2022-06-24 21:06 UTC by JacksonChen666

Fixes dead link for [this link](https://matt.traudt.xyz/posts/2017-12-02-dont-https-your-onions/)

2022-08-05 21:21 UTC, JacksonChen666 commented
i would've deleted my fork if this went through

2022-11-08 12:25 UTC, helix2301 requested changes
I can't get either link to come up for me

2022-11-08 13:37 UTC, helix2301 reviewed
The host for the website seems to be broken/dead, returning 403 on port 80 and port 443 being not open -  NO CHANGE NEEDED

2022-11-20 07:04 UTC, Gargron approved these changes

2022-11-20 07:04 UTC, merged